---
- name: Install Semaphore via Snap
  hosts: GCP
  become: yes

  tasks:
    - name: installation de Snapd
      apt:
        name: snapd
        state: present
        update_cache: yes

    - name: demarrage du service Snapd
      systemd:
        name: snapd
        state: started
        enabled: yes

    - name: Installation de Semaphore
      snap:
        name: semaphore
        state: present

    - name: Stop Semaphore service if running
      command: snap stop semaphore
      
    - name: Create Semaphore directory
      file:
        path: /etc/semaphore
        state: directory
        mode: '0755'

    - name: Create BoltDB directory
      file:
        path: /var/lib/semaphore
        state: directory
        mode: '0755'

    - name: Create Semaphore config file from template
      template:
        src: config.json.j2
        dest: /etc/semaphore/config.json
        mode: '0644'
    
    - name: Initialize Semaphore configuration
      command: >
        semaphore -config /etc/semaphore/config.json -migrate

    - name: Create default admin user
      command: >
        semaphore -config /etc/semaphore/config.json -useradd admin \
        -email admin@example.com -username admin -password Thomas62

    - name: Start Semaphore
      command: snap start semaphore
